apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gin-app-ingress
  namespace: default
  annotations:
    # This ensures that if a user hits /auth/login,
    # the request is sent to the backend as /login
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - host: song-app.test
      http:
        paths:

          # http://song-app.test/song
          - path: /song/?(.*)
            pathType: Prefix
            backend:
              service:
                name: song-api
                port:
                  number: 80

          
          # Access this via http://song-app.test/streaming
          - path: /streaming/?(.*)
            pathType: Prefix
            backend:
              service:
                name: streaming-api
                port:
                  number: 80

          
          
          # Access this via http://song-app.test/user
          - path: /user/?(.*)
            pathType: Prefix
            backend:
              service:
                name: user-api
                port:
                  number: 80
