apiVersion: v1
kind: Secret
metadata:
  # Unique Name 1: This belongs to the Song API
  name: song-api-postgres-creds
  namespace: default
  labels:
    app.kubernetes.io/name: song-api
type: kubernetes.io/basic-auth
stringData:
  username: song_db_owner 
  password: song_db_owner_pswrd

---
apiVersion: v1
kind: Secret
metadata:
  # Unique Name 2: This belongs to the User API
  # Since the name is different, there is no collision.
  name: user-api-postgres-creds
  namespace: default
  labels:
    app.kubernetes.io/name: user-api
type: kubernetes.io/basic-auth
stringData:
  # These keys (username/password) are isolated inside 'user-api-postgres-creds'
  username: user_db_owner 
  password: user_db_owner_pswrd
