apiVersion: v1
kind: Secret
metadata:
  name: pg-user-password
  namespace: default
type: kubernetes.io/basic-auth # CNPG specifically likes this type
stringData: # Using stringData lets you write plain text
  username: META_MUSIC_USER # Kubernetes will convert this to Base64 for you
  password: meta_music_password
