---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pg-user-password
  namespace: default
spec:
  encryptedData:
    password: AgAl5uU+h2sJ+MpO+UjxwT2Hg5Wtj6+7jzCShSUk6/AjT8QMzoTRks9F+0cYSfRIgIKr0OYaqVSgnbRLMEaM8DunL5tOgaQ2bfVhurHac9CZlT4TN0jZeYFuJCyba4AtF7y9mmOVrKMJgS2ifjSz6U+Wbg1ILeJNUwKqg7dV5Y5KHJPcH4YIpMDjIVC+izy8mf4sCS4ZpuwuVmry4PXyiattkSxpNbL9tAYudxELeL2gwxbDo0JpwJbOGhasI1k428jghazjhayBVOhqNsQrJ6FvURrjnLFQQENyX2Wpwh1+1XMZboKP75zIgHA1AeJ8kp391PCL1Rj9QbE8PXnG/x3ge9yIvSpNkn5pGWI2UMF5BSG68W6L34nVxalVOtZQM+kRVlWAC6L/FYoRw6mohpZ8vi7uIQ/ENi0lM7jrOHYrHVUX5lRdtT3u/3s08YJ+PJvjLddXs6NadKhmyw/HsW/tZPDwrnaM1HlrSI2nSqeGTj1ln0b3CpGK6ydvkOPYxLQ5QGnyEA+8PkriSOzODV/Drk+xRKNZDXRitX0DAPuo1r9w2T154HX6Q4+6jpvaTfgo7w736OczPsDxZA+dY8M3SwAfMewzvKaEOm4ywxj8LGEyL+OAZP232RKCI99HdblERWmbrmBLe/HXlxgtRDAM+oePjwHQYL5Ao+cDN1mteZqm5WZu15ybob+lmY498CPxMF77Y6Fat07rJnbxOpzFBfVu
    username: AgCh685aXUI9k5HYqbMTy4CqaGKIg/klmbeWQqKwpngZwzjbJaF+TstJeaIRNbOfYvIHVtg9oc1HeZ5Y9A6oS+lvbhuC6muaecg3vEafkn+Sr3Q1yZI2Nkg8TAZa+VId1ppGpwMtPlvpAthRzGkVxn3s0YpXbNJF4UfqBygw5DJgdwqInBapdTx2HGf7by0b5ZYaJF62DAewD0xBOEGe+pUjC0tYgMJQyrvbTSHGTXff44CMVTeatETYWKb07BaYQBkvtU8Id+NRZN9FHEfcyl64WN/pOiJviyD5qdgVIzAAYqEgkbrIMGfc1rfkU/0XusvP8+JPXXamxI0BcD5AtUiCB2JwXPl8lKhls0Hd2/GweFjaslXfFw+7/gkOvYQh7gV0a/8sUbxoQqjs3wVZS8eDauSPETk46SbgLK7lE3gsMkgtyK9GmvJCmqX+0sTSLK6yoHllq0g9SAX5FBxpBf1eQrls0wJtlqIF+jZXMCGRC80Ozl8Efe+sX/tiNDrgy/8quqYLQZPZH06ccc/vzaEk4PoqxelNz06PetfyGQh4gn+UqEH7V9HnBd+KtCMK8N5YLNJjaPVUfR3JQMgO4xVPK/xaE7+YiFZekJnYBhdkHabNowimOGUDN0VzSA/LIw6qcqqmx/lmTfy3mQc0mv/IG94eK3LhHPKzNMHONk5fahNv9idOTMDoHilEBwcb/LNeN0PyC796dxAerosZ4Nc=
  template:
    metadata:
      creationTimestamp: null
      name: pg-user-password
      namespace: default
    type: kubernetes.io/basic-auth
