{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "song-api-postgres-creds",
    "namespace": "default",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "song-api-postgres-creds",
        "namespace": "default",
        "creationTimestamp": null,
        "labels": {
          "app.kubernetes.io/name": "song-api"
        }
      },
      "type": "kubernetes.io/basic-auth"
    },
    "encryptedData": {
      "password": "AgAyQ1qfM4PclBKzoLC62mOjP52TO4qJzXzKXM1OnluHQrJoqMJRqpKLV7aq5BHTavX8T21VWtO0gC7T/QppWR91KlOB80stIOAmaA8gLJFZ13F/NRbJ+pEkJigvdGwhIRkRFE2mUGFvUZLdqPjVsQa6rRWP3yAFDrKiNYjl2+Aq8iX9B+9ijZO1ikXwcd7uZO1e9oogUOK/ecFGt3s546tmJ1ksU3M6WJ5UKMFbBJmNSYxUVsVJPpCLdRBMwoljmt7XN3C9l7dVxHD/EzRU49n6R4g+JyQdITVPRvhIzYDcrR1qVFy85/qJJ31HG4fe8S8hAIktqMIxFAB43pzKHkZ1kwDGP06yKLvZX8wN2/o/Av1cOWGYVYoG+VUuRN0stnyFgUSjfPOkgTVgm7M8rUtrylDeyld7o2MAsOcBQpHBhnN70VQsBt+zaY0U8CaG8vJ2XsOd9q5Dx0hF+JeSS3MkClnK5qDWcLm1kNJiEPoMu8VOBpu1d9vd6LYBskhHtn2zIvb9uXSyoZYTxRyAVkBXCgGwLvEv/nJw9zsKozuh0T1Yjj7bTUm2WMKuMkaIjmfEvYjKk0omGkivNLAfI46ZtjM2FtjPh4BD/ZH5Chwm84xdj9ZGjLjRcK5T6f4RMB2gkdpHrLbGAlEb7iK7sNjudkdT+pZaZKC/iEmMRdINNyPxbk5VIWnNFzVBqjOp+DLQwyin54HxawFmZYJh2T24wsXX",
      "username": "AgCrSEfw6EWYuejvd0J3cUrmfWAh6NA6P71VNep4/inWMqwvxNxK21WuGuGiAN3I+Cwnd+Dilg9z81HGRSZmtThgdYrds4ZgroRHkTLbWKj9easaICIrVqNEihy0PdszjzPeB4Xo2xcwhLAux6TpPc/VTHhpCg8LMPXii4BAeAckwQ4ooh+hMfqgE80H+fEd3MCctXyrYeJ2oTh9GwwOfcqMD3jkFS+GFvYX7Bc3bB0CAHHu3FgBhlG5a8zT+20LTVMcR4L9dukpSom6nlFWTMhUcuAKWzK2vz63Ruj1A/gHrTDAaGmj1WqOR2Kchydks5sOAG4tntA6x6xLn6MBCEZ3ylS19YLHx1G8KiCfy8S2jFUH+yNe2rg/LSX9THGIbYnkkPoTP4tzMorZ/VhTiupbM0HrWTQTFMysuvyUIbwF2tKwQ410ea3NSBFPcshTiyn7EzxiMbTAFdBfi9IYjRdWqOjeG1wVNbNzeuWT6InEXlq4sVl0sXwvxbMVn8e9GoJt5bNiXeMrGkZu5RIM5Tfe0+/Cn8VFQykCEf+Kb1qxqPK8dLcsVxEo815E40V8rsz2wh2qcrpX6n5/I42ZE1j7umhNCjeTHGF3PYxHR/P5pbvV6IdSnQ31ZUVrd3ix0JprEftfvywTRmljHiBekc43kxwPCvDzYMGA7bsPknCDVoocSF9214W6Lrd4nTedH39vQcUBxrJBU5GCJc5s"
    }
  }
}
{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "user-api-postgres-creds",
    "namespace": "default",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "user-api-postgres-creds",
        "namespace": "default",
        "creationTimestamp": null,
        "labels": {
          "app.kubernetes.io/name": "user-api"
        }
      },
      "type": "kubernetes.io/basic-auth"
    },
    "encryptedData": {
      "password": "AgCtIe/auUp0h6La2yzEEqNXIHmPxrGSiYqxALPb6fqOATAVkzl1CM/iInpKY7GmjR6S29mYNO83UFM580xksNdyuxPq7guNjpAsoLfqEWAeD9CPqPn5Y04zt0vxuLdjrhg4TSt3wv83Sc9U+Hg2SHjNrSUufXkHBmrH7jZVjfu5e/Y9ajLsnswnxcTbipRLO2Rfa1+Z/x2rtkRTQuSVmghw0ky4exa2SXyCcgyOyu0p532O5fNBKQ0ngnTSi24wig24OLrl9QizWcpnN1Z7om+lP88GikAdLJhyVUl+bbx4lA4Kz7l1ac9VyAYiMkCoP8C7nBxtnB5YbXdvxIW6oSlvjX6jUM6ROjme60TRSmLfOg89f7h3bjw96UGT5uAvrRiFRYRVBLSZu1xCKAhSKDWGnESo2zRdUs1KJXCVOfcEBUg2GLqh2+Y0nlL3BfU4cmPlsNbcAVoPHC47YsOxhnr3SxrHZ7f/rT3zanzLOUzG+sLnStTvEx3/p3CcTgSBAfEdfIgjqXvRw2kgiQfydPSc7WMZioV2aK5kalcNxh2LuSFHc9//Xq9ezc0kY9ZciEMOaVWkDj4Svma7q6mzkMVnzsSc2U+upgVw5iDbvWVyoh2nEE3VlbPLpSGYRUdxpPPonZkwqpkpwlQ4a1IpNWMn7tGAkBhfd310Fip6l+/z/qbgTShjxXdpN8T7G6ajOe5kaVjVLeh0A7GAPZ7zTVIS2+17",
      "username": "AgCuDiFw1wtLO4DMCK2moORjHZxlu4O1Cu7JXKvnopLGWQ82zTGvCzKjayN2EaPtmxmEN+wCAeJo5Ulntu2m6WcCoXYbBCzD+SWcdgBDV6Gjr1C5ILbbPnwu8ymRlHRYYY4/EDpCdjh5I0d7T+YVSLx9zQAS06WtCtKLwsIElqmxktSUorcxsypWuG6+CKmxieuNIE7UfeHmSR0KpHzTyTeDti3Sxb2eZaeKfW9iNON0K8Pis87EKu4LXmDtVCeMi8Yy5eJsAl1geR/Hn9lzxCZJ0gVYi9V766YNCIPeLY8AXANk/eYGj6RMMTcjrd1zKRjO/irIA8pun0uXJolI52jwDvE+68PjKLowNbiDVGYIBiAJz+/eacqSlLP/hfC8YBtPidjfMl3JQQYOa9to+4IlCSY21ucyiAX69s2JNLTE5lypGrK5iqOLxrWQG4lL2jLIING8yrSy31ylr6MTYN8wSjbWiBCGyv3zuS0kq9+7j2EPW22qkMyePUjoSCfOV18vuRrNOzJGNA3FZ51eYswQ9Oriy32AJqWfGOXzXkTXFUyn9PS37zdqvSv0IS39rvdxSe64SjD4qXS5+OpL3EPCgLy/JMeTO+xKMykReP2IIZn6AhHZ51sCslgRVP4QnNivMtLO8IpaiDb2DrLEwbFlPpT9UwdXTI2/SljTqyTgWAGO7azzt7rm9ST1JCbD4k+rwA/kFMYLn0efhXEZ"
    }
  }
}
