{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "redis-app-secrets",
    "namespace": "default",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "redis-app-secrets",
        "namespace": "default",
        "creationTimestamp": null
      },
      "type": "Opaque"
    },
    "encryptedData": {
      "song-redis-creds": "AgAs4PGmMSBdvsnE4JMfGNfKboIaIjj1SU+O2HFnXOXRGDdZlDa/XmwkvqaddMwzJCSfCdpn/hjhMEOfuFS87r5lUzW74T6JEE/1Blpfvte2ltSqQMCzZCDuFuSTOD6iCmWSmMloC9yb/patI2wjk2uC4eFppTDRS5Gmg3AzttnBnDpE5a6f0iInjpP43IJTSy5o9tvrFDo3SzwB6Sw/bQeBzG2q2hwB7UANYYBDNjzGvrQrWgG+6FS1eXwVy4l1ljdacX80om+gMPgwo91ZoKUHh7opWU/EeKrWVSteZMTr05etu8YlplDKSGusXDZ326tu9OYe7dnUQ+71NYPcG7ZEx96Ah9934NicghcGlMIN9aoDGvQv59JA4X3t63KEnFxvCMzcElTzwFyjTOOGXfX2fNUTBcifa37crPWqXhHDxG9faSOuvbLeu2ZgMs9JWsil6uKocEW43lfBMlQybYtPlY9oO5V8xsg2mAf9xjTl6VM7jYAlgIUxTiTK8TV34TH9nJeGcwbnoeY2nguMW648bmKWo0Mw+XtonbehxU13H0HT7t3iHR4Js9UPNGEsNEs7ExdZK9kuAkNIDAFCozYBGNI/KRGTgx/nUW4MFTgg1qkG6jtKdmtr7uZV0g4NuwdJaEJgsQXLDOjbKhg+QxGUrWwIDl2R8MUnOMIFybA7UjNAk6xN1orYowqMhn4peJtoq8hzblmY1Kvx/PSm",
      "streaming-redis-creds": "AgA0Pp/aqmoQSzs2ujTVtd8aXcLQ1CVekk8ckwj7R1FhoqLqM4JO9KIxwqbS2OtdqYUHXoHapifnyXcfw0RsGL7W+NPYaf+gTTP7vvp/SbRfemq4ICtuHPZHkm7f7RwbJRNQ23oCrGrL+2udkTbn4bEuaSg2jUbwn23JAQqUTdTq5qfPjAIzVKTmtdXhbksbjULHg+B6x7dtTXGe7fK7ppYUtw/M4UjOlp/GCGju9sdhm+EWI4j5mabeWtYD0ulBo4F9gvpN617Dw+nI8L+gvUJ4F/p8Yg2N0nzPDYhO9TdZ49PmYdxMPIzZ4/3NIBNkNy1gEj3aLCNtDznPsiJJxMLrHjBa2iRpC+N/98OB2og+Hon2lg/dvvI/YBev0J+D8L+ohTZP0qyfHKqRm1zGkfeIq/+m4ioYwGupbmejAnokYUMs4PwjI3pUZL8DobcRtMoJH8yP9kcNMIbugoG/4P+8jyGTztJsushvRcRo9RrRZkx+9AqKXctoqJP1TEw/uTCorAYDuI6WdMwzZpl98R1cKHwtVGUHExU+1kDbtEvkIaJWV+s1kaIjguM5CpzJaCYD2i2Ayy30F+IEt3t6cdVrAAl3W+oOx7EQkynxq98urUHQi8aoHkv6ikAp6Pgsv10EZ5A9UgjQ29mdpU7nuql8lqw2KCv97kWvBa3SCnrhuZUDCAGjLvj7dKUjjxn1Ay25vHGxKj+QrMCUx056sHsivEQ="
    }
  }
}
