{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "user-api-secrets",
    "namespace": "default",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "user-api-secrets",
        "namespace": "default",
        "creationTimestamp": null
      },
      "type": "Opaque"
    },
    "encryptedData": {
      "JWT_SECRET": "AgAVsnWfXyhhPpBQJrZcC4h5VfdNO6xyuxUOdK4uzFFekhVb6aDDnD44pW/4tSh3SJVG9euXzpr0mM/sb4qkuDgJhAUqCMvicNIHa5NFieKxp7TP7MWlyoBUt36QU3Oq1BNKKoEBuVnRa1MxkQqRKgPjVnyHqHnlJnCzqNPPL6wU2vN5TnZlivK3cBVGOmoXfw/yvcvNQegcpPP96LGSn5oeD/4HRdUVm4h1tj9qcuPWa0uhRPhyufi5jF6KZh8swYj1KYxc+Sk72NnV7T1WkfPJ3sGjxkIkKJaTyZI+jEJQhASzJOkgtjBcBhSxQslt/L8DIsNQ42tiHrXHTIWG+0Pm08yTQ2Hz/p7obWH6cT4t5wX6onFHBFsVOTQJvR/qys9CEenc3xLvUbcpjiJ/pt1gPnF6aMF9FZfqJoaqTCpJrejCNMJAb5NM/2gv26C7xdlsJGeMzIGTnpnmUupyjLH97cf52l74bN1lUJNT99N5t9opXvyyPDR5plIhDTQ/qP+9PDjmMutsEeOEPzFDGarJjXQ4yGfz1TdwrkvYWHtFiA69b1CasT8bEBeAH+9wR07rnHQX51lusL/ICsmfzPBDXOazVcExu+FbX/thutnNxVM2isI9WK7llZsEMBfAKDtQqTDuLo+6u/ld54/wpIcPhtrwbkJmuS8E8s8V+zJ0m/STzUrcNqmZKvGAIRsiLlqDys5dWZTWySh+jaabE0DnHDR64Q=="
    }
  }
}
