services:
  # ====================== BACKEND SERVICES ======================
  user-service:
    build: ../services/user-service
    container_name: user-service
    ports:
      - "8080:8080"
    image: meta/user-api:v1.0
    env_file:
      - ../services/user-service/.env
      
    # depends_on:
    #   postgres:
    #     condition: service_healthy
    #   redis:
    #     condition: service_healthy
    networks:
      - app-network

 

  song-service:
    build: ../services/song-service
    container_name: song-service
    ports:
      - "8080:8080"
    image: meta/song-api:v1.0
    env_file:
      - ../services/song-service/.env
    # depends_on:
    #   song-db:
    #     condition: service_healthy
    #   redis-song-cache:
    #     condition: service_healthy
    networks:
      - app-network
  
  # song-db:
  #   image: postgres:16-alpine
  #   container_name: song-db
  #   env_file:
  #     - ../services/song-service/.env
  #   volumes:
  #     - song_db_data:/var/lib/postgresql/data
  #     - ./song-service/config/init.sql:/docker-entrypoint-initdb.d/init.sql
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 5
  #   networks:
  #     - private-song-service-network
  
  # redis-song-cache:
  #   image: redis:7-alpine
  #   container_name: redis-song-cache
  #   volumes:
  #     # Use a relative path to a local folder (e.g., ./redis-data)
  #     - ./redis-data:/data
  #   # 'appendonly yes' is the most reliable way to save to local files
  #   command: redis-server --appendonly yes --loglevel warning
  #   healthcheck:
  #     test: ["CMD", "redis-cli", "ping"]
  #     interval: 5s
  #     timeout: 3s
  #     retries: 5
  #   networks:
  #     - private-song-service-network

  # ====================== STREAMING SERVICES ======================
  streaming-service:
    build: ../services/streaming-service
    image: meta/streaming-api:v1.0
    container_name: streaming-service
    ports:
      - "8080:8080"
    env_file:
      - ../services/streaming-service/.env  
    networks:
      - app-network

  # ====================== API GATEWAY (Nginx) ======================
  # api-gateway:
  #   image: nginx:alpine
  #   container_name: api-gateway
  #   ports:
  #     - "8000:80"
  #   volumes:
  #     - ../api-gateway/nginx.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - user-service
  #     - song-service
  #     - streaming-service
  #   networks:
  #     - app-network
  

  # ====================== DEVELOPER TOOLS ======================
  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #   ports:
  #     - "5050:80"
  #   depends_on:
  #     - postgres
  #   networks:
  #     - app-network


# volumes:
#   song_db_data:

networks:
  app-network:
    driver: bridge
