apiVersion: v1
kind: ConfigMap
metadata:
  name: gin-app-config
  namespace: default
data:
  SEGMENT_DURATION: "10"
  SERVER_PORT: "8080"
  POSTGRES_HOST: "pg-production-rw" # Points to the CNPG Primary service
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "app_db"
  REDIS_ADDR: "redis-song-cache:6379"
  REDIS_DB: "0"
  MAX_PAGE_SIZE: "10"
